version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - run:
          name : Install Dependencies
          command : npm install
      - run:
          name: Install typescript
          command : npm install typescript -g
      - run:
          name : Run In DevMode
          command : npm run prod
