version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build:
    machine:
      enabled: true
  steps:
    - add_ssh_keys:
        fingerprints:
          - 'c7:65:60:3b:f2:c6:29:57:07:a1:14:81:8e:7f:be:10'

    - checkout

    - run:
        name: Build and deploy to dimosian8docker1/5and_dollar
        Comand:
          #Build Image
          docker build -t dimosian8docker1/5and_dollar .
          #Deploy image
          docker push dimosian8docker1/5and_dollar:latest
          #Update Container
          ssh ubuntu@ec2-52-89-78-51.us-west-2.compute.amazonaws.com 'docker service update --image dimosian8docker1/5and_dollar:latest SERVICE_NAME
