version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'b8:cb:79:f2:0a:bd:5d:cd:fc:3a:3e:fb:a2:f8:37:d4'

      - checkout

      - run:
          name: Build and deploy to dimosian8docker1/5and_dollar
          command: |
            # Authorize
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            # Build Image
            docker build -t dimosian8docker1/5and_dollar .
            # Deploy image
            docker push dimosian8docker1/5and_dollar:latest
            # Update Container
            ssh -i ubuntu@ec2-52-89-78-51.us-west-2.compute.amazonaws.com 'docker service update --image dimosian8docker1/5and_dollar:latest sandDollar'
