version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '05:9b:b4:f8:e0:60:45:34:f8:0d:e7:36:e2:ae:7e:d1:6e:32:2a:75:c8:fa:59:ce:fa:15:21:53:8c:c2:3c:c8'

      - checkout

      - run:
          name: Build and deploy to dimosian8docker1/5and_dollar
          command: |
            # Authorize
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            # Build Image
            docker build -t dimosian8docker1/5and_dollar .
            # Deploy image
            docker push dimosian8docker1/5and_dollar:latest
            # Authorize Docker from Ec2
            ssh ubuntu@ec2-52-43-216-70.us-west-2.compute.amazonaws.com 'docker login -u dimosian8docker1 -p Scario1996@'
            # get first Containerized app
            ssh ubuntu@ec2-52-43-216-70.us-west-2.compute.amazonaws.com 'docker pull dimosian8docker1/5and_dollar:latest'
