version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '4a:9b:a7:5b:62:25:64:88:6f:d8:61:a8:4a:5c:dc:f2:36:47:b3:ff'

      - checkout

      - run:
          name: Build and deploy to dimosian8docker1/5and_dollar
          command: |
            # Authorize
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            # Build Image
            docker build -t dimosian8docker1/5and_dollar .
            # Deploy image
            docker push dimosian8docker1/5and_dollar:latest
            # Update Container
            ssh ubuntu@ec2-34-220-255-16.us-west-2.compute.amazonaws.com 'docker service update --image dimosian8docker1/5and_dollar:latest sandDollar'
